import Head from "next/head";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import Coursemain from "../components/Courses/Coursemain";
import JoinUs from "../components/Courses/JoinUs";
import Faq from "../components/Courses/Faq";

export default function Courses() {
  return (
    <div className="bg-[#F5F5F5]">
      <Head>
        <title>Courses</title>
        <meta name="description" content="Generated by leopard" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header color />
      <Coursemain />
      <JoinUs
        imgsrc="/images/CoursesJonUs.svg"
        title="Want to Control your Future?"
        description="Loem ipsum makcov task vanade Hemiskade mevatuledes"
        btncolor="black"
      />
      <Faq />
      <Footer />
    </div>
  );
}
