import Register from "../components/Auth/Register";
import Head from "next/head";

export default function Register() {
  return (
    <div className="">
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by leopard" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Register />
    </div>
  );
}
